Jk_Fitness/Controllers/LoginController.cs
using DataLayer;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.Text.Json;
using System.Runtime.Serialization;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using ServiceLayer.Password;
using System.Text;
using DataLayer.Models;

namespace Jk_Fitness.Controllers
{
    public class LoginController : Controller
    {
        private readonly LogInService logInService;
        WebResponce webResponce = null;
        public LoginController(LogInService logInService)
        {
            this.logInService = logInService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult<WebResponce> ValidateLogIn([FromBody] Employee employe)
        {
            webResponce = logInService.ListLogInInfo(employe);
            if(webResponce.Code == 1)
            {
                Response.Cookies.Append("jkfitness.cookie", Crypto.EncryptString(((Employee)webResponce.Data).EmployeeId));
                Response.Cookies.Append("Role", ((Employee)webResponce.Data).UserType);
            }
            return webResponce;
        }

        [HttpPost]
        public ActionResult<WebResponce> ConfirmPassword([FromBody] Employee employe)
        {
            webResponce = logInService.ConfirmPassword(employe);
            return webResponce;
        }

        [HttpPost]
        public ActionResult<WebResponce> UpdatePassword([FromBody] Employee employe)
        {
            try
            {
                employe.ModifiedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = logInService.UpdatePassword(employe);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpGet]
        public ActionResult<WebResponce> SignOutLogin()
        {
            try
            {
                Response.Cookies.Delete("jkfitness.cookie");
                webResponce = new WebResponce()
                {
                    Code = 1,
                    Message = "Success"
                };
                return webResponce;
            }
            catch (Exception ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = ex.Message.ToString()
                };
                return webResponce;
            }
        }

        #region ForgotPassword
        public IActionResult ForgotPassword()
        {
            return View();
        }


        [HttpPost]
        public ActionResult<WebResponce> RequestPassword([FromBody] Employee employe)
        {
            try
            {
                webResponce = logInService.RequestNewPassword(employe);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
        #endregion

        #region Members Login
        public IActionResult MemberLogin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult<WebResponce> ValidateMemberLogIn([FromBody] MemberShip member)
        {
            webResponce = logInService.MemberLogInInfo(member);
            if (webResponce.Code == 1)
            {
                Response.Cookies.Append("jkfitness.member", Crypto.EncryptString(((MemberShip)webResponce.Data).MemberId.ToString()));
            }
            return webResponce;
        }
        [HttpPost]
        public ActionResult<WebResponce> MemberConfirmPassword([FromBody] MemberShip member)
        {
            webResponce = logInService.ConfirmMemberPassword(member);
            return webResponce;
        }
        [HttpPost]
        public ActionResult<WebResponce> UpdateMemberPassword([FromBody] MemberShip member)
        {
            try
            {
                webResponce = logInService.UpdatePassword(member);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
        #endregion

        #region MemberForgotPassword
        public IActionResult MemberForgotPassword()
        {
            return View();
        }


        [HttpPost]
        public ActionResult<WebResponce> MemberRequestPassword([FromBody] MemberShip member)
        {
            try
            {
                webResponce = logInService.RequestNewPassword(member);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpGet]
        public ActionResult<WebResponce> MemberSignOutLogin()
        {
            try
            {
                Response.Cookies.Delete("jkfitness.member");
                webResponce = new WebResponce()
                {
                    Code = 1,
                    Message = "Success"
                };
                return webResponce;
            }
            catch (Exception ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = ex.Message.ToString()
                };
                return webResponce;
            }
        }
        #endregion

        #region initial page
        public IActionResult Initial()
        {
            return View();
        }
        #endregion
    }
}

Jk_Fitness/Controllers/MemberHomeController.cs
using DataLayer.Models;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer;
using ServiceLayer.Password;
using ServiceLayer.VMmodel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Jk_Fitness.Controllers
{
    public class MemberHomeController : Controller
    {
        private readonly EmployeeService employee;
        private readonly MemberShipService MemberShip;
        WebResponce webResponce = null;

        public MemberHomeController(EmployeeService employee, MemberShipService MemberShip)
        {
            this.employee = employee;
            this.MemberShip = MemberShip;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public WebResponce GetTrainers()
        {
            try
            {
                webResponce = employee.ListTrainerDetails(Convert.ToInt32(Crypto.DecryptString(Request.Cookies["jkfitness.member"])));
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce NewTrainingRequest(TrainingVM training)
        {
            try
            {
                webResponce = employee.NewTrainingRequest(training);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce SaveNewTrainingRequest(RequestTrainers requestTrainers)
        {
            try
            {
                webResponce = employee.SaveNewTrainingRequest(requestTrainers);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce TrainingHistroy(TrainingVM training)
        {
            try
            {
                webResponce = employee.MemberTrainingHistroy(training);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpGet]
        public WebResponce GetTrainingStartandEndYear()
        {
            try
            {
                webResponce = employee.GetTrainingStartandEndYear();
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

          [HttpGet]
        public WebResponce GetMemberDetails()
        {
            try
            {
                webResponce = MemberShip.GetMemberDetailsById(Convert.ToInt32(Crypto.DecryptString(Request.Cookies["jkfitness.member"])));
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
    }
}

Jk_Fitness/Views/MemberHome/Index.cshtml
@{ Layout = null; }

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Member Home</title>
    <link rel="icon" href="~/dist/img/jkfitness.jpeg" />
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.min.css">
    <link href="~/css/custom.css" rel="stylesheet" />
    <link href="~/css/ecommerce.css" rel="stylesheet" />
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@9.5.3/dist/sweetalert2.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.5.3/dist/sweetalert2.all.min.js"></script>
    <link href="~/plugins/DataTableNew/datatables.min.css" rel="stylesheet" />
</head>
<body>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="form-group row col-md-12">
                        <div class="col-md-11">
                            <h2>Welcome <span id="memberName"></span></h2>
                        </div>
                        <div class="col-md-1">
                            <a href="/" onclick="SignOut()" class="dropdown-item"><i class="fa fa-power-off"></i> Logout</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="col-md-12 form-group row">
                        <div class="col-md-5">
                            <div class="row">
                                <h2>New Training Request</h2>
                            </div>
                            <br />
                            <div class="form-group row ">
                                <label class="control-label col-md-4 col-sm-4 ">Date</label>
                                <div class="input-group date col-md-8 col-sm-8" id="Tdate" data-target-input="nearest">
                                    <input type="text" id="Date" class="form-control datetimepicker-input" data-target="#Tdate" data-toggle="datetimepicker" />
                                    <div class="input-group-append" data-target="#Tdate" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row ">
                                <label class="control-label col-md-4 col-sm-4 ">Trainer</label>
                                <div class="col-md-8 col-sm-8">
                                    <select class="form-control" id="Trainer"></select>
                                </div>
                            </div>
                            <div class="form-group row col-md-3 col-sm-3" style="float:right;">
                                <button type="button" id="btnSearch" class="btn btn-secondary col-md-12 col-sm-12"><i class="fa fa-search"></i> Search</button>
                            </div>
                            <div class="card-footer table-responsive">
                                <table id="tblNewTraining" class="table table-bordered table-striped tblNewTraining">
                                    <thead>
                                        <tr>
                                            <th>Time Slot</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>
                                    <tbody id="tbodyid1">
                                    </tbody>
                                </table>
                                <div class="msg-block" id="noRecords1">
                                    <label>No Records found.</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-1"></div>
                        <div class="col-md-6">
                            <div class="row">
                                <h2>Training History</h2>
                            </div>
                            <br />
                            <div class="form-group row ">
                                <div class="form-group col-md-4">
                                    <label>Year</label>
                                    <div class="col-md-12 col-sm-12 ">
                                        <select class="form-control" id="Year"></select>
                                    </div>
                                </div>
                                <div class="form-group col-md-4">
                                    <label>Month</label>
                                    <div class="col-md-12 col-sm-12">
                                        <select class="form-control" id="Month"></select>
                                    </div>
                                </div>

                                @*<div class="col-md-2 col-sm-2"></div>*@
                            </div>
                            <div class="card-footer table-responsive">
                                <table id="tblTrainingHistroy" class="table table-bordered table-striped tblTrainingHistroy">
                                    <thead>
                                        <tr>
                                            <th>Date</th>
                                            <th>Time Slot</th>
                                            <th>Trainer Name</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>
                                    <tbody id="tbodyid">
                                    </tbody>
                                </table>
                                <div class="msg-block" id="noRecords2">
                                    <label>No Records found.</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12 form-group row">
                        <div class="col-md-6 form-group">
                            <div class="row">
                                <h2>Selected Package Information</h2>
                            </div>
                            <div class="row">
                                <label class="control-label col-md-3 col-sm-3 ">Package Name</label>
                                <div class="col-md-6 col-sm-6">
                                    <input type="text" id="pName" class="form-control" disabled>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <label class="control-label col-md-3 col-sm-3 ">Package Amount</label>
                                <div class="col-md-6 col-sm-6">
                                    <input type="text" id="pAmount" class="form-control" disabled>
                                </div>
                            </div>
                            <br />
                            <div class="row">
                                <label class="control-label col-md-3 col-sm-3 ">Package Expiration</label>
                                <div class="col-md-6 col-sm-6">
                                    <input type="text" id="pExpire" class="form-control" disabled>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 form-group">
                            <div class="row">
                                <h2>Payment History</h2>
                            </div>
                            <div class="card-footer table-responsive">
                                <table id="example1" class="table table-bordered table-striped tblMember">
                                    <thead>
                                        <tr>
                                            <th>Package Type</th>
                                            <th>Amount</th>
                                            <th>Payment Date</th>
                                            <th>Payment Status</th>
                                        </tr>
                                    </thead>
                                    <tbody id="tbodyid">
                                    </tbody>
                                </table>
                                <div class="msg-block" id="noRecords">
                                    <label>No Records found.</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div id="wait" class="loading-gif"><img src="~/dist/img/Loading.gif" width="70" height="70" /><br></div>
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
        <input type="hidden" id="GetTrainers" value="@Url.Action("GetTrainers", "MemberHome")" />
        <input type="hidden" id="NewTrainingRequest" value="@Url.Action("NewTrainingRequest", "MemberHome")" />
        <input type="hidden" id="SaveNewTrainingRequest" value="@Url.Action("SaveNewTrainingRequest", "MemberHome")" />
        <input type="hidden" id="TrainingHistroy" value="@Url.Action("TrainingHistroy", "MemberHome")" />
        <input type="hidden" id="SignOutLogin" value="@Url.Action("MemberSignOutLogin","Login")" />
        <input type="hidden" id="LoginHome" value="@Url.Action("Initial","Login")" />
        <input type="hidden" id="GetStartandEndYear" value="@Url.Action("GetTrainingStartandEndYear", "MemberHome")" />
        <input type="hidden" id="GetMemberDetails" value="@Url.Action("GetMemberDetails", "MemberHome")" />
    </div>



    <script src="~/js/page.memberHome.js"></script>

    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.js"></script>
    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- ChartJS -->
    <script src="~/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <!--<script src="~/plugins/sparklines/sparkline.js"></script>-->
    <!-- JQVMap -->
    <!--<script src="~/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>-->
    <!-- jQuery Knob Chart -->
    <script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    @*<script src="~/dist/js/pages/dashboard.js"></script>*@
</body>
</html>