Jk_Fitness/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DataLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ServiceLayer;
using ServiceLayer.Password;
using ServiceLayer.VMmodel;

namespace Jk_Fitness.Controllers
{
    [ValidCookie]
    public class EmployeeController : Controller
    {

        private readonly EmployeeService employee;
        private readonly SettingsService Setting;
        WebResponce webResponce = null;
        public EmployeeController(EmployeeService employee, SettingsService Setting)
        {
            this.employee = employee;
            this.Setting = Setting;
        }
        public IActionResult Index()
        {
            var userType = Request.Cookies["Role"];
            List<int> result1 = Setting.GetUserRightsbyUsertype(userType);
            if (result1.Count() > 0)
            {
                ViewBag.Add = result1[4];
                ViewBag.Edit = result1[5];
                ViewBag.Delete = result1[6];
                ViewBag.View = result1[7];
            }
            return View();
        }

        [HttpGet]
        public WebResponce GetBranchDetails()
        {
            try
            {
                webResponce = employee.ListBranches();
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpGet]
        public WebResponce GetUserTypeDetails()
        {
            try
            {
                webResponce = employee.ListUserType();
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce SaveEmployees(EmployeeVM files)
        {
            try
            {
                Employee employe = JsonConvert.DeserializeObject<Employee>(files.Employee);
                if (files.file !=null)
                {
                    using (var ms = new MemoryStream())
                    {
                        files.file.CopyTo(ms);
                        var fileBytes = ms.ToArray();
                        employe.Image = fileBytes; 
                    }
                }
                employe.CreatedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]); 
                webResponce = employee.SaveEmployees(employe);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpGet]
        public WebResponce GetEmployeeDetails()
        {
            try
            {
                webResponce = employee.ListEmployeeDetails();
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce UpdateEmployees(EmployeeVM files)
        {
            try
            {
                Employee employe = JsonConvert.DeserializeObject<Employee>(files.Employee);
                if (files.file != null)
                {
                    using (var ms = new MemoryStream())
                    {
                        files.file.CopyTo(ms);
                        var fileBytes = ms.ToArray();
                        employe.Image = fileBytes; 
                    }
                }
                employe.ModifiedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = employee.UpdateEmployees(employe);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce DeleteEmployees([FromBody] Employee employe)
        {
            try
            {
                webResponce = employee.DeleteEmployee(employe);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce SearchEmployees([FromBody] Employee employe)
        {
            try
            {
                webResponce = employee.SearchEmployee(employe);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpGet]
        public WebResponce GetMembershipDetails(int memberId)
        {
            try
            {
                webResponce = employee.GetMembershipDetails(memberId);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        #region SalaryManagement
        public IActionResult Salary()
        {
            var userType = Request.Cookies["Role"];
            List<int> result1 = Setting.GetUserRightsbyUsertype(userType);
            if (result1.Count() > 0)
            {
                ViewBag.Edit = result1[29];
            }
            return View();
        }


        [HttpPost]
        public WebResponce UpdateSalary([FromBody] Employee employe)
        {
            try
            {
                employe.ModifiedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = employee.UpdateSalary(employe);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
        #endregion

        #region Profile
        public IActionResult Profile()
        {
            return View();
        }

        [HttpGet]
        public WebResponce GetProfileDetails()
        {
            try
            {
                webResponce = employee.GetEmployeeById(Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]));
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
        #endregion
    }
}

Jk_Fitness/Controllers/ProductController.cs
using DataLayer.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ServiceLayer;
using ServiceLayer.Password;
using ServiceLayer.VMmodel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Jk_Fitness.Controllers
{
    public class ProductController : Controller
    {
        private readonly ProductService products;
        private readonly SettingsService Setting;
        WebResponce webResponce = null;

        public ProductController(ProductService products, SettingsService Setting)
        {
            this.products = products;
            this.Setting = Setting;
        }
        public IActionResult Index()
        {
            var userType = Request.Cookies["Role"];
            List<int> result1 = Setting.GetUserRightsbyUsertype(userType);
            if (result1.Count() > 0)
            {
                ViewBag.Add = result1[39];
                ViewBag.Edit = result1[40];
                ViewBag.Delete = result1[41];
            }
            return View();
        }

        public IActionResult ProductList()
        {
            return View();
        }

        public IActionResult ViewSoldProducts()
        {
            var userType = Request.Cookies["Role"];
            List<int> result1 = Setting.GetUserRightsbyUsertype(userType);
            if (result1.Count() > 0)
            {
                ViewBag.Delete = result1[60];
            }
            return View();
        }

        [HttpPost]
        public WebResponce SaveProduct(ProductVM files)
        {
            try
            {
                Product product = JsonConvert.DeserializeObject<Product>(files.Product);
                if (files.file != null)
                {
                    using (var ms = new MemoryStream())
                    {
                        files.file.CopyTo(ms);
                        var fileBytes = ms.ToArray();
                        product.ProductImage = fileBytes;
                    }
                }
                product.CreatedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = products.SaveProduct(product);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce UpdateProduct(ProductVM files)
        {
            try
            {
                Product product = JsonConvert.DeserializeObject<Product>(files.Product);
                if (files.file != null)
                {
                    using (var ms = new MemoryStream())
                    {
                        files.file.CopyTo(ms);
                        var fileBytes = ms.ToArray();
                        product.ProductImage = fileBytes;
                    }
                }
                product.ModifiedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = products.UpdateProduct(product);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpGet]
        public WebResponce GetProductDetails(string BranchId)
        {
            try
            {
                webResponce = products.ListProductDetails(BranchId);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce DeleteProduct([FromBody] Product product)
        {
            try
            {
                webResponce = products.DeleteProduct(product);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpGet]
        public WebResponce UpdateProductQuantity(SoldProducts soldProducts)
        {
            try
            {
                soldProducts.CreatedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);

                webResponce = products.UpdateProductQuantity(soldProducts);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce LoadSoldProductsList(string branch, int year, int month)
        {
            try
            {
                webResponce = products.LoadSoldProductsList(branch, year, month);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce DeleteSoldProduct([FromBody] SoldProducts soldProducts)
        {
            try
            {
                webResponce = products.DeleteSoldProduct(soldProducts);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        #region
        public IActionResult ViewSoldProductsReport()
        {
            var userType = Request.Cookies["Role"];
            List<int> result1 = Setting.GetUserRightsbyUsertype(userType);
            if (result1.Count() > 0)
            {
                ViewBag.Delete = result1[60];
            }
            return View();
        }
        #endregion
    }
}

Jk_Fitness/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="form-group">
                    <h3 class="card-title">Product Details</h3>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Branch</label>
                            <div class="col-md-12 col-sm-12 ">
                                <select class="form-control" id="BranchforSearch"></select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Product Name</label>
                            <div class="col-md-12 col-sm-12 ">
                                <input type="text" id="PnameforSearch" class="form-control" placeholder="Enter Product Name">
                            </div>
                        </div>
                        <div class="form-group">
                            <div style="float:right">
                                <button type="button" id="btnAdd" class="btn btn-success"><i class="fa fa-plus"></i> Add New</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer table-responsive">
                <table id="tblProduct" class="table table-bordered table-striped tblProduct">
                    <thead>
                        <tr>
                            <th>Product Name</th>
                            <th>Branch</th>
                            <th>Available Stock</th>
                            <th>Price</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody id="tbodyid">
                    </tbody>
                </table>
                <div class="msg-block" id="noRecords">
                    <label>No Records found.</label>
                </div>
            </div>
            <div id="wait" class="loading-gif"><img src="~/dist/img/Loading.gif" width="70" height="70" /><br></div>
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
    <input type="hidden" id="GetProductDetails" value="@Url.Action("GetProductDetails","Product")" />
    <input type="hidden" id="GetBranchDetails" value="@Url.Action("GetBranchDetails", "Membership")" />
    <input type="hidden" id="UpdateProduct" value="@Url.Action("UpdateProduct", "Product")" />
    <input type="hidden" id="SaveProducts" value="@Url.Action("SaveProduct", "Product")" />
    <input type="hidden" id="DeleteProduct" value="@Url.Action("DeleteProduct", "Product")" />

    <input type="hidden" id="add" value="@ViewBag.Add" />
    <input type="hidden" id="edit" value="@ViewBag.Edit" />
    <input type="hidden" id="delete" value="@ViewBag.Delete" />
    <input type="hidden" id="view" value="@ViewBag.View" />
</div>

<div id="ProModal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel"><strong>Product Details</strong></h4>
                <button type="button" class="close" data-dismiss="modal" onclick="Cancel()">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="x_panel">
                    <div class="x_content">
                        <form id="formUser" class="form-horizontal form-label-left" enctype="multipart/form-data">
                            <input type="hidden" value="0" id="ProductId" />

                            <div class="form-group row" style="justify-content:center;">
                                <div id="imgPreview" class="img-thumbnail" style="display:block">
                                    <img src="~/dist/img/default.jpg" id="targetImg" style="width:100%;height:250px;" />

                                </div>
                            </div>
                            <div class="form-group row ">
                                <label class="control-label col-md-3 col-sm-3 ">Product Image</label>
                                <div class="col-md-9 col-sm-9">
                                    <div class="custom-file">
                                        <input type="file" id="imageBrowes" class="form-control custom-file-input" />
                                        <label class="custom-file-label">Choose File....</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row ">
                                <label class="control-label col-md-3 col-sm-3">Product Name</label>
                                <div class="col-md-9 col-sm-9">
                                    <input type="text" required class="form-control" id="Productname">
                                </div>
                            </div>
                            <div class="form-group row ">
                                <label class="control-label col-md-3 col-sm-3">Product Description</label>
                                <div class="col-md-9 col-sm-9">
                                    <textarea class="form-control" id="ProductDescription"></textarea>
                                </div>
                            </div>
                            <div class="form-group row ">
                                <label class="control-label col-md-3 col-sm-3 ">Branch</label>
                                <div class="col-md-9 col-sm-9">
                                    <select class="form-control" id="Branch"></select>
                                </div>
                            </div>
                            <div class="form-group row ">
                                <label class="control-label col-md-3 col-sm-3 ">Available Stock</label>
                                <div class="col-md-9 col-sm-9">
                                    <input type="text" required id="Stock" class="form-control">
                                </div>
                            </div>
                            <div class="form-group row ">
                                <label class="control-label col-md-3 col-sm-3 ">Price</label>
                                <div class="col-md-9 col-sm-9">
                                    <input type="text" id="Price" class="form-control">
                                </div>
                            </div>

                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div style="float:right">
                                    <button type="button" id="btnSave" class="btn btn-success">Save</button>
                                    <button type="button" id="btnCancel" onclick="Cancel()" class="btn btn-warning">Cancel</button>
                                </div>
                            </div>
                            <div id="waitform" class="loading-gif"><img src="~/dist/img/Loading.gif" width="70" height="70" /><br></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/js/page.product.js"></script>

Jk_Fitness/Views/Product/ProductList.cshtml
@{
    ViewData["Title"] = "ProductList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .searchBox {
        background-color: lightgrey;
        padding: 10px;
    }
</style>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="form-group">
                    <h3 class="card-title">Products List</h3>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-8 row searchBox">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Branch</label>
                                <div class="col-md-12 col-sm-12 ">
                                    <select class="form-control" id="BranchforSearch"></select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Product Name</label>
                                <div class="col-md-12 col-sm-12 ">
                                    <input type="text" id="PnameforSearch" class="form-control" placeholder="Enter Product Name">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3" style="padding-top:9px; padding-left:20px;">
                        <div class="form-group">
                            <label>Sold Date</label>
                            <div class="input-group date col-md-12 col-sm-12" id="date" data-target-input="nearest">
                                <input type="text" id="soldDate" class="form-control datetimepicker-input" data-target="#date" data-toggle="datetimepicker" />
                                <div class="input-group-append" data-target="#date" data-toggle="datetimepicker">
                                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <div class="cui-ecommerce--catalog">
                    <div class="row productHolder">

                    </div>
                </div>

            </div>
            <div id="wait" class="loading-gif"><img src="~/dist/img/Loading.gif" width="70" height="70" /><br></div>
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
    <input type="hidden" id="GetProductDetails" value="@Url.Action("GetProductDetails","Product")" />
    <input type="hidden" id="GetBranchDetails" value="@Url.Action("GetBranchDetails", "Employee")" />
    <input type="hidden" id="UpdateProductQuantity" value="@Url.Action("UpdateProductQuantity", "Product")" />
    <input type="hidden" id="SaveProducts" value="@Url.Action("SaveProduct", "Product")" />
    <input type="hidden" id="DeleteProduct" value="@Url.Action("DeleteProduct", "Product")" />

    <input type="hidden" id="add" value="@ViewBag.Add" />
    <input type="hidden" id="edit" value="@ViewBag.Edit" />
    <input type="hidden" id="delete" value="@ViewBag.Delete" />
    <input type="hidden" id="view" value="@ViewBag.View" />
</div>


<script src="~/js/page.productList.js"></script>

Jk_Fitness/Views/Product/ViewSoldProducts.cshtml
@{
    ViewData["Title"] = "ViewSoldProducts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="form-group">
                    <h3 class="card-title">Sold Products Details</h3>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Branch</label>
                            <div class="col-md-12 col-sm-12 ">
                                <select class="form-control" id="Branch"></select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Year</label>
                            <div class="col-md-12 col-sm-12 ">
                                <select class="form-control" id="Year"></select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Month</label>
                            <div class="col-md-12 col-sm-12 ">
                                <select class="form-control" id="Month"></select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer table-responsive">
                <table id="tblSoldProduct" class="table table-bordered table-striped tblSoldProduct">
                    <thead>
                        <tr>
                            <th>Product Id</th>
                            <th>Product Name</th>
                            <th>Branch</th>
                            <th>Price Per Product</th>
                            <th>Sold Price Per Product</th>
                            <th>Quantity</th>
                            <th>Total Sold Price</th>
                            <th>Sold Date</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody id="tbodyid">
                    </tbody>
                </table>
                <div class="msg-block" id="noRecords">
                    <label>No Records found.</label>
                </div>
            </div>
            <div id="wait" class="loading-gif"><img src="~/dist/img/Loading.gif" width="70" height="70" /><br></div>
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
    <input type="hidden" id="GetSoldProducts" value="@Url.Action("LoadSoldProductsList","Product")" />
    <input type="hidden" id="GetBranchDetails" value="@Url.Action("GetBranchDetails", "Membership")" />
    <input type="hidden" id="GetStartandEndYear" value="@Url.Action("GetStartandEndYear", "PaymentsExpenses")" />
    <input type="hidden" id="DeleteSoldProduct" value="@Url.Action("DeleteSoldProduct", "Product")" />

    <input type="hidden" id="delete" value="@ViewBag.Delete" />

</div>

<script src="~/js/page.viewSold-Products.js"></script>