Jk_Fitness/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DataLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ServiceLayer;
using ServiceLayer.Password;
using ServiceLayer.VMmodel;

namespace Jk_Fitness.Controllers
{
    [ValidCookie]
    public class EmployeeController : Controller
    {

        private readonly EmployeeService employee;
        private readonly SettingsService Setting;
        WebResponce webResponce = null;
        public EmployeeController(EmployeeService employee, SettingsService Setting)
        {
            this.employee = employee;
            this.Setting = Setting;
        }
        public IActionResult Index()
        {
            var userType = Request.Cookies["Role"];
            List<int> result1 = Setting.GetUserRightsbyUsertype(userType);
            if (result1.Count() > 0)
            {
                ViewBag.Add = result1[4];
                ViewBag.Edit = result1[5];
                ViewBag.Delete = result1[6];
                ViewBag.View = result1[7];
            }
            return View();
        }

        [HttpGet]
        public WebResponce GetBranchDetails()
        {
            try
            {
                webResponce = employee.ListBranches();
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpGet]
        public WebResponce GetUserTypeDetails()
        {
            try
            {
                webResponce = employee.ListUserType();
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce SaveEmployees(EmployeeVM files)
        {
            try
            {
                Employee employe = JsonConvert.DeserializeObject<Employee>(files.Employee);
                if (files.file !=null)
                {
                    using (var ms = new MemoryStream())
                    {
                        files.file.CopyTo(ms);
                        var fileBytes = ms.ToArray();
                        employe.Image = fileBytes; 
                    }
                }
                employe.CreatedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]); 
                webResponce = employee.SaveEmployees(employe);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpGet]
        public WebResponce GetEmployeeDetails()
        {
            try
            {
                webResponce = employee.ListEmployeeDetails();
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce UpdateEmployees(EmployeeVM files)
        {
            try
            {
                Employee employe = JsonConvert.DeserializeObject<Employee>(files.Employee);
                if (files.file != null)
                {
                    using (var ms = new MemoryStream())
                    {
                        files.file.CopyTo(ms);
                        var fileBytes = ms.ToArray();
                        employe.Image = fileBytes; 
                    }
                }
                employe.ModifiedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = employee.UpdateEmployees(employe);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce DeleteEmployees([FromBody] Employee employe)
        {
            try
            {
                webResponce = employee.DeleteEmployee(employe);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce SearchEmployees([FromBody] Employee employe)
        {
            try
            {
                webResponce = employee.SearchEmployee(employe);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpGet]
        public WebResponce GetMembershipDetails(int memberId)
        {
            try
            {
                webResponce = employee.GetMembershipDetails(memberId);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        #region SalaryManagement
        public IActionResult Salary()
        {
            var userType = Request.Cookies["Role"];
            List<int> result1 = Setting.GetUserRightsbyUsertype(userType);
            if (result1.Count() > 0)
            {
                ViewBag.Edit = result1[29];
            }
            return View();
        }


        [HttpPost]
        public WebResponce UpdateSalary([FromBody] Employee employe)
        {
            try
            {
                employe.ModifiedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = employee.UpdateSalary(employe);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
        #endregion

        #region Profile
        public IActionResult Profile()
        {
            return View();
        }

        [HttpGet]
        public WebResponce GetProfileDetails()
        {
            try
            {
                webResponce = employee.GetEmployeeById(Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]));
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
        #endregion
    }
}

Jk_Fitness/Controllers/SettingsController.cs
using DataLayer;
using DataLayer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer;
using ServiceLayer.Password;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Jk_Fitness.Controllers
{
    [ValidCookie]
    public class SettingsController : Controller
    {
        private readonly SettingsService Setting;
        WebResponce webResponce = null;

        public SettingsController(SettingsService Setting) {
            this.Setting = Setting;
        }

        #region - Branch
        public IActionResult Branch()
        {
            var userType = Request.Cookies["Role"];
            List<int> result1 = Setting.GetUserRightsbyUsertype(userType);
            if (result1.Count() > 0) {
                ViewBag.Add = result1[17];
                ViewBag.Edit= result1[18];
                ViewBag.Delete = result1[19];
            }
            return View();
        }

        [HttpPost]
        public WebResponce SaveBranch([FromBody] Branch branch)
        {
            try
            {
                branch.CreatedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = Setting.SaveBranch(branch);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }


        [HttpGet]
        public WebResponce GetBranchDetails()
        {
            try
            {
                webResponce = Setting.ListBranchDetails();
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce GetBranchById([FromBody] Branch branch)
        {
            try
            {
                webResponce = Setting.GetBranchById(branch.Id);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce Updatebranch([FromBody] Branch branch)
        {
            try
            {
                branch.ModifiedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = Setting.UpdateBranch(branch);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce DeleteBranch([FromBody] Branch branch)
        {
            try
            {
                webResponce = Setting.DeleteBranch(branch);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce SearchBranch([FromBody] Branch branch)
        {
            try
            {
                webResponce = Setting.SearchBranch(branch);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
        #endregion

        #region Expenses Types
        public IActionResult ExpensesType()
        {
            var userType = Request.Cookies["Role"];
            List<int> result1 = Setting.GetUserRightsbyUsertype(userType);
            if (result1.Count() > 0)
            {
                ViewBag.Add = result1[21];
                ViewBag.Edit = result1[22];
                ViewBag.Delete = result1[23];
            }
            return View();
        }
        [HttpGet]
        public WebResponce GetExpensesDetails()
        {
            try
            {
                webResponce = Setting.ListExpensesDetails();
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
        [HttpPost]
        public WebResponce SaveExpensesType([FromBody] ExpensesTypes expenseType)
        {
            try
            {
                expenseType.CreatedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = Setting.SaveExpensesType(expenseType);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
        [HttpPost]
        public WebResponce DeleteExpenseType([FromBody] ExpensesTypes expenseType)
        {
            try
            {
                webResponce = Setting.DeleteExpeseType(expenseType);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
        [HttpPost]
        public WebResponce GetExpenseTypeById([FromBody] ExpensesTypes expenseType)
        {
            try
            {
                webResponce = Setting.GetExpenseTypeById(expenseType.Id);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
        [HttpPost]
        public WebResponce UpdateExpenseType([FromBody] ExpensesTypes expenseType)
        {
            try
            {
                expenseType.ModifiedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = Setting.UpdateExpenseType(expenseType);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
        [HttpPost]
        public WebResponce SearchExpensesType([FromBody] ExpensesTypes expenseType)
        {
            try
            {
                webResponce = Setting.SearchExpenseTypes(expenseType);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
        #endregion

        #region Memebership Types
        public IActionResult MembershipType()
        {
            var userType = Request.Cookies["Role"];
            List<int> result1 = Setting.GetUserRightsbyUsertype(userType);
            if (result1.Count() > 0)
            {
                ViewBag.Add = result1[25];
                ViewBag.Edit = result1[26];
                ViewBag.Delete = result1[27];
            }
            return View();
        }
        [HttpGet]
        public WebResponce GetMembershipTypeDetails()
        {
            try
            {
                webResponce = Setting.ListMembershipTypesDetails();
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpGet]
        public WebResponce GetEnabledMembershipTypeDetails()
        {
            try
            {
                webResponce = Setting.ListMembershipTypesDetails(true);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
        [HttpPost]
        public WebResponce SaveMembershipType([FromBody] MembershipTypes membershipType)
        {
            try
            {
                membershipType.CreatedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = Setting.SaveMembershipType(membershipType);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,

Jk_Fitness/Views/Settings/InternalExpenses.cshtml
@{
    ViewData["Title"] = "InternalExpenses";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="form-group">
                    <h3 class="card-title">Display Internal Expenses</h3>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Branch</label>
                            <div class="col-md-12 col-sm-12 ">
                                <select class="form-control" id="Branch"></select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Expense Type</label>
                            <div class="col-md-12 col-sm-12">
                                <select class="form-control" id="expenseType"></select>
                            </div>
                        </div>
                        <div class="form-group">
                            <div style="float:right">
                                <button type="button" id="btnAdd" class="btn btn-success"><i class="fa fa-plus"></i> Add New</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer table-responsive">
                <table id="tblInternalExpense" class="table table-bordered table-striped tblInternalExpense">
                    <thead>
                        <tr>
                            <th>Employee Id</th>
                            <th>Expense Type</th>
                            <th>Expense Amount</th>
                            <th>Payment Date</th>
                            <th>Description</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody id="tbodyid">
                    </tbody>
                </table>
                <div class="msg-block" id="noRecords">
                    <label>No Records found.</label>
                </div>
            </div>
            <div id="wait" class="loading-gif"><img src="~/dist/img/Loading.gif" width="70" height="70" /><br></div>
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
    <input type="hidden" id="GetEmployeeDetails" value="@Url.Action("GetEmployeeDetails", "Settings")" />
    <input type="hidden" id="GetExpensesType" value="@Url.Action("LoadExpensesType", "Settings")" />
    <input type="hidden" id="SaveInternalExpenses" value="@Url.Action("SaveInternalExpenses", "Settings")" />
    <input type="hidden" id="UpdateInternalExpenses" value="@Url.Action("UpdateInternalExpenses", "Settings")" />
    <input type="hidden" id="GetInternalExpenses" value="@Url.Action("LoadInternalExpenses", "Settings")" />
    <input type="hidden" id="DeleteInternalExpense" value="@Url.Action("DeleteInternalExpense", "Settings")" />
    <input type="hidden" id="SearchExpensesType" value="@Url.Action("SearchExpensesType", "Settings")" />
    <input type="hidden" id="GetBranchDetails" value="@Url.Action("GetBranchDetails", "Employee")" />
    <input type="hidden" id="add" value="@ViewBag.Add" />
    <input type="hidden" id="edit" value="@ViewBag.Edit" />
    <input type="hidden" id="delete" value="@ViewBag.Delete" />
</div>

<div id="IntModal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel"><strong>Employee Details</strong></h4>
                <button type="button" class="close" data-dismiss="modal" onclick="Cancel()">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="x_panel">
                    <div class="x_content">
                        <form id="formUser" class="form-horizontal form-label-left" enctype="multipart/form-data">
                            <input type="hidden" value="0" id="Id" />
                            <div class="form-group row" id="MemFind" style="display:flex">
                                <label class="control-label col-md-3 col-sm-3">EmployeeId</label>
                                <div class="col-md-3 col-sm-3">
                                    <input type="text" class="form-control" id="EmployeeId">
                                </div>
                                <div class="col-md-3 col-sm-3">
                                    <button type="button" id="btnSearch" class="btn btn-success form-control"><i class="fa fa-search"></i> Find</button>
                                </div>
                                <div class="col-md-3 col-sm-3">
                                    <button type="button" id="btnClear" class="btn btn-warning form-control">Clear</button>
                                </div>
                            </div>
                            <div class="form-group row ">
                                <label class="control-label col-md-3 col-sm-3 ">Employee Name</label>
                                <div class="col-md-9 col-sm-9">
                                    <input type="text" id="Employeename" class="form-control" disabled>
                                </div>
                            </div>
                            <div class="form-group row ">
                                <label class="control-label col-md-3 col-sm-3 ">Branch</label>
                                <div class="col-md-9 col-sm-9">
                                    <input type="text" id="EmpBranch" class="form-control" disabled>
                                    <input type="hidden" id="branchCode" />
                                </div>
                            </div>
                            <div class="form-group row ">
                                <label class="control-label col-md-3 col-sm-3 ">Expenses Type</label>
                                <div class="col-md-9 col-sm-9">
                                    <select class="form-control" id="Expensecode"></select>
                                </div>
                            </div>
                            <div class="form-group row ">
                                <label class="control-label col-md-3 col-sm-3 ">Expenses Amount </label>
                                <div class="col-md-9 col-sm-9">
                                    <input type="text" id="ExpenseAmount" class="form-control">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="control-label col-md-3 col-sm-3 ">Payment Date</label>
                                <div class="input-group date col-md-9 col-sm-9" id="Pdate" data-target-input="nearest">
                                    <input type="text" id="Paymentdate" class="form-control datetimepicker-input" data-target="#Pdate" data-toggle="datetimepicker" />
                                    <div class="input-group-append" data-target="#Pdate" data-toggle="datetimepicker">
                                        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row ">
                                <label class="control-label col-md-3 col-sm-3">Description</label>
                                <div class="col-md-9 col-sm-9">
                                    <textarea class="form-control" id="Description"></textarea>
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div style="float:right">
                                    <button type="button" id="btnAddInternalExpenses" class="btn btn-success">Save</button>
                                    <button type="button" id="btnCancel" onclick="Cancel()" class="btn btn-warning">Cancel</button>
                                </div>
                            </div>
                            <div id="waitform" class="loading-gif"><img src="~/dist/img/Loading.gif" width="70" height="70" /><br></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/js/page.internal-expenses.js"></script>

Jk_Fitness/Views/Settings/MenuRights.cshtml
@{
    ViewData["Title"] = "MenuRights";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="form-group">
                    <h3 class="card-title">Roles and Access Rights</h3>
                </div>
            </div>
            <div class="card-footer table-responsive">
                <table id="tblMenu" class="table table-bordered table-striped tblMenu">
                    <thead>
                        <tr>
                            <th>Main Menu</th>
                            <th>Admin</th>
                            <th>Staff</th>
                            <th>Temporary Staff</th>
                        </tr>
                    </thead>
                    <tbody id="tbodyid">
                    </tbody>
                </table>
                <div class="msg-block" id="noRecords">
                    <label>No Records found.</label>
                </div>
            </div>
            <div id="wait" class="loading-gif"><img src="~/dist/img/Loading.gif" width="70" height="70" /><br></div>
        </div>
        <!-- /.card -->
    </div>
    <!-- /.col -->
    <input type="hidden" id="GetMenuRights" value="@Url.Action("GetMenuRights", "Settings")" />
    <input type="hidden" id="UpdateMenuRights" value="@Url.Action("UpdateMenuRights", "Settings")" />
</div>

<script src="~/js/page.menuRights.js"></script>