Jk_Fitness/Controllers/MailboxController.cs
using DataLayer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using QuickMailer;
using ServiceLayer;
using ServiceLayer.Email;
using ServiceLayer.EmailAttachment;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;

namespace Jk_Fitness.Controllers
{
    [ValidCookie]
    public class MailboxController : Controller
    {
        private readonly MailSettings _mailSettings;
        private readonly MailBoxService mailBoxService;
        WebResponce webResponce = null;

        public MailboxController(IOptions<MailSettings> mailSettings, MailBoxService mailBoxService)
        {
            _mailSettings = mailSettings.Value;
            this.mailBoxService = mailBoxService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public bool MailSending(MailAttachment mailAttachment)
        {
            List<string> ToEmails = new List<string>();
            Email email = new Email();
            ToEmails = GetValidMail(mailAttachment.ToEmail);


            List<Attachment> attachments = new List<Attachment>();
            if (mailAttachment.File != null)
            {
                Attachment attachment = new Attachment(mailAttachment.File.OpenReadStream(), mailAttachment.File.FileName);
                attachments.Add(attachment);
            }
            bool IsSend = email.SendEmail(ToEmails, _mailSettings.Mail, _mailSettings.Password, mailAttachment.Subject, mailAttachment.Body, null, null, attachments);
            return IsSend;
        }

        public List<string> GetValidMail(string mails)
        {
            List<string> emailAddresses = new List<string>();
            Email email = new Email();
            if (!string.IsNullOrEmpty(mails))
            {
                var Emails = mails.Split(',');
                foreach (var mail in Emails)
                {
                    bool isValid = email.IsValidEmail(mail.Trim());
                    if (isValid)
                    {
                        emailAddresses.Add(mail.Trim());
                    }
                }
            }
            return emailAddresses;
        }

        [HttpPost]
        public WebResponce GetMemberDetails(MemberShip Member)
        {
            try
            {
                webResponce = mailBoxService.ListMemberShipDetails(Member);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }
    }
}

Jk_Fitness/Controllers/MembershipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataLayer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer;
using ServiceLayer.Password;
using ServiceLayer.VMmodel;

namespace Jk_Fitness.Controllers
{
    [ValidCookie]
    public class MembershipController : Controller
    {
        private readonly MemberShipService MemberShip;
        private readonly SettingsService Setting;
        WebResponce webResponce = null;

        public MembershipController(MemberShipService MemberShip, SettingsService Setting)
        {
            this.MemberShip = MemberShip;
            this.Setting = Setting;
        }
        public IActionResult Index()
        {
            var userType = Request.Cookies["Role"];
            List<int> result1 = Setting.GetUserRightsbyUsertype(userType);
            if (result1.Count() > 0)
            {
                ViewBag.Add = result1[9];
                ViewBag.Edit = result1[10];
                ViewBag.Delete = result1[11];
                ViewBag.View = result1[12];
            }
            return View();
        }

        [HttpPost]
        public WebResponce SaveMember(MemberShip Member)
        {
            try
            {
                Member.CreatedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = MemberShip.SaveMemberShipDetails(Member);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce GetMemberDetails(MemberShip Member)
        {
            try
            {
                webResponce = MemberShip.ListMemberShipDetails(Member);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce GetMemberShipById([FromBody] MemberShip Member)
        {
            try
            {
                webResponce = MemberShip.GetMemberShipDetailsById(Member.MemberId);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce UpdateMemberShip( MemberShip Member)
        {
            try
            {
                Member.ModifiedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = MemberShip.UpdateMemberShipDetails(Member);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce DeleteMemberShip([FromBody] MemberShip member)
        {
            try
            {
                webResponce = MemberShip.DeleteMemberShpDetails(member);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce SearchMembers([FromBody] MemberShip member)
        {
            try
            {
                webResponce = MemberShip.SearchMemberShipDetails(member);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }


        [HttpGet]
        public WebResponce GetBranchDetails()
        {
            try
            {
                webResponce = MemberShip.ListBranches(Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]));
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        public IActionResult MembersService()
        {
            return View();
        }

        #region MembersAttendance

        public IActionResult MembershipAttendance()
        {
            var userType = Request.Cookies["Role"];
            List<int> result1 = Setting.GetUserRightsbyUsertype(userType);
            if (result1.Count() > 0)
            {
                ViewBag.Edit = result1[14];
                ViewBag.Delete = result1[15];
            }
            return View();
        }

        public IActionResult ViewMembershipAttendance()
        {
            return View();
        }

        [HttpPost]
        public WebResponce ViewMemberShipAttendanceDetails(AttendancesVM attendances)
        {
            try
            {
                webResponce = MemberShip.ViewMemberShipAttendanceDetails(attendances);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce LoadMemberShipAttendanceDetails(AttendancesVM attendances)
        {
            try
            {
                webResponce = MemberShip.LoadMemberShipAttendanceDetails(attendances);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce SaveMemberAttendance(MembersAttendance Attendance)
        {
            try
            {
                Attendance.CreatedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = MemberShip.SaveMemberShipAttendance(Attendance);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce UpdateMemberAttendance(MembersAttendance Attendance)
        {
            try
            {
                Attendance.ModifiedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = MemberShip.UpdateMemberShipAttendance(Attendance);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce DeleteMemberAttendance([FromBody] MembersAttendance Attendance)
        {
            try
            {
                webResponce = MemberShip.DeleteMemberAttendance(Attendance);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        #endregion

        #region Temporary Membership
        public IActionResult ProvisionalMember()
        {
            var userType = Request.Cookies["Role"];
            List<int> result1 = Setting.GetUserRightsbyUsertype(userType);
            if (result1.Count() > 0)
            {
                ViewBag.Add = result1[55];
                ViewBag.Edit = result1[56];
                ViewBag.Delete = result1[57];
            }
            return View();
        }

        [HttpPost]
        public WebResponce SaveProvisionalMember(ProvisionalMember provisionalMember)
        {
            try
            {
                provisionalMember.CreatedBy = Crypto.DecryptString(Request.Cookies["jkfitness.cookie"]);
                webResponce = MemberShip.SaveProvisionalMemberShipDetails(provisionalMember);
                return webResponce;
            }
            catch (Exception Ex)
            {
                webResponce = new WebResponce()
                {
                    Code = -1,
                    Message = Ex.Message
                };
                return webResponce;
            }
        }

        [HttpPost]
        public WebResponce GetProvisionalMemberDetails(ProvisionalMember provisionalMember)
        {
            try
            {
                webResponce = MemberShip.ListProvisionalMemberShipDetails(provisionalMember);
                return webResponce;
            }
            catch (Exception Ex)
            {

Jk_Fitness/Views/Mailbox/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="card card-primary card-outline">
            <div class="card-header">
                <h3 class="card-title">Compose Mail</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div class="custom-control custom-checkbox col-md-2">
                        <input class="custom-control-input" type="checkbox" id="Manual" value="true">
                        <label for="Manual" class="custom-control-label">Manual</label>
                    </div>
                    <span id="MailCount" style="color: red; display:none"></span>
                </div>

                <br>
                <div class="row" id="FilterOpt" style="display:none">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Branch</label>
                            <select class="form-control col-md-12 col-sm-12" id="Branch"></select>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Status</label>
                            <select class="form-control col-md-12 col-sm-12" id="Status"></select>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Gender</label>
                            <select class="form-control col-md-12 col-sm-12" id="Gender"></select>
                        </div>
                    </div>

                </div>
                <div class="form-group" id="ToOpt" style="display:flex">
                    <input class="form-control" id="To" placeholder="To:">
                </div>
                <div class="form-group">
                    <input class="form-control" id="Subject" placeholder="Subject:">
                </div>
                <div class="form-group">
                    <textarea id="compose-textarea" class="form-control" style="height: 300px">                 
                    </textarea>
                </div>
                <div class="form-group">
                    @*<div class="btn btn-default btn-file">
                            <i class="fas fa-paperclip"></i> Attachment
                            <input type="file" id="attachment" name="attachment">
                        </div>*@
                    <div class="custom-file">
                        <input type="file" id="attachment" class="form-control custom-file-input" />
                        <label class="custom-file-label" id="fileLabelName">Choose Attachment File....</label>
                    </div>
                    @*<p class="help-block">Max. 32MB</p>*@
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <div class="float-right">
                    @* <button type="button" class="btn btn-default"><i class="fas fa-pencil-alt"></i> Draft</button>*@
                    <button type="submit" id="save" class="btn btn-primary"><i class="far fa-envelope"></i> Send</button>
                </div>
                <button type="reset" class="btn btn-default" id="Discard"><i class="fas fa-times"></i> Discard</button>
            </div>
            <!-- /.card-footer -->
        </div>
        <!-- /.card -->
    </div>
    <div id="waitform" style="display:none;position:fixed;top:50%;left:50%;padding:2px;"><img src="~/dist/img/Loading.gif" width="70" height="70" /><br></div>
    <!-- /.col -->
    <input type="hidden" id="SentMailPath" value="@Url.Action("MailSending","Mailbox")" />
    <input type="hidden" id="GetBranchDetails" value="@Url.Action("GetBranchDetails", "Membership")" />
    <input type="hidden" id="GetMemberDetails" value="@Url.Action("GetMemberDetails", "Mailbox")" />
</div>


<script src="~/js/page.mail.js"></script>